# -*- coding: utf-8 -*-
"""김선우국통0324.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EHVd2VmKkkW2Tc9oFAYQ8wlRzIqns2YQ
"""

sentence='i love you'
reverse=''
for char in sentence:
    reverse=char+reverse
    print(reverse)
    # 역순으로 출력

"""break 문 , continue문







"""

for i in range(10): 
    if i==5:
        break
    print(i)
print('End of program')

for i in range(10): 
    if i==5:
        continue
    print(i)
print('End of program')
# 짝수나 홀수만 출력 하는 코드에서도 사용

dan = int(input('몇단을 계산?:'))
for i in range(1,10):
    result=i*dan
    print(dan,'*',i,'=',result)

    #구구단 계산기

"""진법변환
10진수: 한자링는 0부터 9까지 표현
2진수 (binary) #0,1 로 표현
8진수 (octal digit) #0부터 7까지 표현
16진수 (hexa digit) #0부터 9까지는 동일, (10)A(11)B(12)C(13)D(14)E(15)F로 
"""

decimal =10
result=''
while (decimal >0):
    reminder = decimal %2
    decimal = decimal //2
    result=str(reminder)+result
print(result)

print(0b1010) #2진수 1010을 10진수로 변환: 1*8+0*4+1*2+0*1

"""십진수 543 = 5*100+4*10+3*1"""

print(0b11)

print(0o11) #8+1

print(0xA)

print(bin(127))

print(hex(127))

import random #이진 탐색

random_number=random.randint(1,100)
user_number=int(input())

while random_number != user_number:
    if user_number>random_number:
        print('down')
    else:
        print('up')
    user_number=int(input())



else:
    print('정답입니다')

import random
guess_num = random.randint(1,10)
user_num = int(input())
cnt = 0
while user_num != guess_num:
    cnt+=1
    if user_num>guess_num:
        print('down')
    else:
        print('up')
    user_num=int(input())
else:
    print('정답')

print('구구단 몇단을 계산할까요')
dan=1
while dan != 0:
    dan = int(input())
    if dan ==0 :
        break
    if not(dan>2 and dan<=9):
        print('wrong number')
        continue
    else:
        print('구구단 계산')
        for i in range(1,10):
            print(dan*i)
        print('구구단 몇 단을 계산할 까요?:')
print('구구단 종료')

#교과점수 평균 계산

kor_score=[14,55,66,34,88]
math_score=[55,66,77,87,33]
eng_score=[78,53,25,77,44]
midterm_score=[kor_score,math_score,eng_score]

student_score=[0,0,0,0,0]

i=0
for subject in midterm_score:
    for score in subject:
        student_score[i] += score #학생마다 개별로 교과 점수를 저장
        i +=1  #학생 인덱스 구분
    i=0   #학생 인덱스 초기화
else:
    a,b,c,d,e = student_score  # 언패킹
    student_average=[a/3,b/3,c/3,d/3,e/3]
    print(student_average)

kor_score=[14,55,66,34,88]
math_score=[55,66,77,87,33]
eng_score=[78,53,25,77,44]
midterm_score=[kor_score,math_score,eng_score]

student_score=[0,0,0,0,0]

for subject in midterm_score:
    i=0
    for score in subject:
        student_score[i] += score #학생마다 개별로 교과 점수를 저장
        i +=1  #학생 인덱스 구분
    
else:
    a,b,c,d,e = student_score  # 언패킹
    student_average=[a/3,b/3,c/3,d/3,e/3]
    print(student_average)

a =[1,2,3,4,5]
a.append(10)
print(a)
print(a.pop())
print(a.pop())
print(a)

#입력한 텍스트를 역순으로 추출하는 프로그램
word = input('input a word:')
word_list=list(word)
print(word_list)
result=[]
for _ in range (len(word_list)):
    result.append(word_list.pop()) #pop된 값을 result에 다시 추가. 역순의 리스트가 형성됨
print(result)
print(word[::-1])

a=[1,2,3,4,5]
a.append(10)
a.append(20)
print(a.pop(0)) #pop(0)를 하게 되면 큐의 자료구조 처럼 앞에서 부터 반환됨
print(a.pop(0))

print(a)

t=(1,2,3)
print(type(t))

tt=1,2,3
print(type(tt))

ttt=1,
print(type(ttt)) #데이터 값을 변경할 수 없다.