# -*- coding: utf-8 -*-
"""김선우국통0602

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w8KJlTLcRR3erBEhB68McU5gOf2qV-TC

Numpy
"""

import numpy as np
y=np.ones([3,4])  # 배열의 값을 1로 채움
print(y)

import numpy as np
x=np.array([[1,3,5],[2,4,6]])
print(x[0])

print(x.mean())
print(x[1].mean())
print(x.shape)  #(몇행, 몇열) 인지?

list1 = [[1, 11], [2, 12], [3, 13]]
print(list1[:][1])  # 의도하지  않은  결과  출력 
print(list1[:, 1])  # Error 발생

import numpy as np
list1 = [[1, 11], [2, 12], [3, 13]] 
np_ary = np.array(list1) 
print(np_ary[:, 1]) #전체 에서 인덱스 1번에 해당되는 값만 출력

import numpy as np
list2=[[1,11,111],[2,12,222],[3,13,333]] 
np_ary2=np.array(list2)
print(np_ary2[:,2])

import math
math.sqrt(2)

import numpy as np
np.sqrt([2,3,4])
# 넘파이를 사용하면 리스트 형태에서도 루트 사용가능

import numpy as np 
a = np.arange(15) 
print(a)

import numpy as np
a = np.arange(15).reshape(3, 5) 
print(a)

import numpy as np
a = np.arange(15).reshape(3, 5)
print(a[1][1])

import numpy as np 
zero_vector = np.zeros(3) 
print(zero_vector)

zero_matrix = np.zeros((4, 3)) 
print(zero_matrix)

import numpy as np
my_array = np.zeros(15).reshape(3,5)
my_array += 4
my_array

zero_vector = np.zeros(5) 
zero_vector

#print를 안붙이면 array문구와 함께 출력

import numpy as np 
a = np.array([[1,2],[3,4]]) 
print(a.transpose())

# 전치 행렬로 반환

import numpy as np 
x=np.array([1,2,3]) 
y=np.array([4,5,6]) 
z=x+y
print(z)

#넘파이를 통하여 배열간의 자유로운 연산가능

import numpy as np
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x[1])
print(x[:,1])

x = np.array([[1,2,3],[4,5,6],[7,8,9]])
y = np.array([[2,3,4],[5,6,7],[8,9,10]])
print(x[:,1]+y[:,1])
print(x*y)

a= np.array([10,20,30,40,50,60,70])
i=[1,3,5]
print(a[i])

import numpy as np
a = np.array([10, 20, 30, 40, 50, 60, 70]) 
b = np.array(a[1:6:2])
print('b:', b)
b[1] = 10
print('b:', b) 
print('a:', a) 
type(b)

import numpy as np
a = np.array([10, 20, 30, 40, 50, 60, 70]) 
b= a>50
print(b)

"""데이터 시각화(matplot)"""

import matplotlib.pyplot as plt 
y = [1, 2, 3, 4, 5]
plt.plot(y) 
plt.show()

import matplotlib.pyplot as plt 
y = [13, 16, 15, 18, 16, 17, 16] 
plt.plot(y)
plt.show()

import matplotlib.pyplot as plt 
y = [13, 16, 15, 18, 16, 17, 16] 
plt.plot(range(len(y)), y)

x = ['Mon', 'Tue', 'Wed', 'Thur', 'Fri', 'Sat', 'Sun'] 
y = [13, 16, 15, 18, 16, 17, 16]
plt.plot(x, y);

x = ['Mon', 'Tue', 'Wed', 'Thur', 'Fri', 'Sat', 'Sun'] 
y = [13, 16, 15, 18, 16, 17, 16]
plt.plot(x, y);
plt.xlabel('Daily')
plt.ylabel('No. of Books Sold')

# 라벨(label) 입력
#  xlabel(): x축의  라벨을  입력
#  ylabel(): y축의  라벨을  입력

x = ['Mon', 'Tue', 'Wed', 'Thur', 'Fri', 'Sat', 'Sun'] 
y1 = [13, 16, 15, 18, 16, 17, 16]
y2 = [17, 14, 17, 16, 15, 15, 14]
plt.plot(x, y1)
plt.plot(x, y2)
plt.xlabel('Daily')
plt.ylabel('No. of Books Sold')

x = ['Mon', 'Tue', 'Wed', 'Thur', 'Fri', 'Sat', 'Sun'] 
y1 = [13, 16, 15, 18, 16, 17, 16]
y2 = [17, 14, 17, 16, 15, 15, 14]
plt.plot(x, y1, label='Sold')
plt.plot(x, y2, label='On Shelves')
plt.xlabel('Daily')
plt.ylabel('No. of Books Sold')
plt.legend(loc="upper left")
# 범례 붙이기

x = ['Mon', 'Tue', 'Wed', 'Thur', 'Fri', 'Sat', 'Sun'] 
y1 = [13, 16, 15, 18, 16, 17, 16]
y2 = [17, 14, 17, 16, 15, 15, 14]
plt.plot(x, y1, label='Sold')
plt.plot(x, y2, label='On Shelves')
plt.xlabel('Daily')
plt.ylabel('No. of Books Sold')
plt.legend(loc="upper left")
plt.title('Le Petit Prince: Sold & Left')

import numpy as np
points=np.array([[1,1],[1,2],[1,3],[2,1],[2,2],[2,3],[3,1],[3,2],[3,3]])
p =np.array([2.5,2])
import matplotlib.pyplot as plt
plt.plot(points[:,0],points[:,1], "ro")
plt.plot(p[0],p[1],"bo")

x=np.linspace(0,10,20)
y1=x**2
y2=x**1.5
plt.plot(x,y1,"bo-",linewidth=2,markersize=12,label="First")
plt.plot(x,y2,"gs-",linewidth=2,markersize=12,label="Seocond")
plt.xlabel("x")
plt.ylabel("y")
plt.axis([-0.5,10.5,-5,105])
plt.legend(loc="upper left")
plt.savefig("mplot.pdf")

x=np.random.rand(30)
y=np.random.rand(30)
colors = np.random.rand(30)
shape = np.pi * (np.random.rand(30)*20)**2
plt.scatter(x,y,s=shape,c=colors,marker="*",alpha=0.7)
plt.show()