# -*- coding: utf-8 -*-
"""김선우국통_과제2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a6jtdjzgRK-lK8WUVtszshPbwn1PVKk2
"""

import csv
import matplotlib.pyplot as plt

dir = '/content/report2.csv.csv'
f = open(dir, 'r', encoding='cp949')
data = csv.reader(f, delimiter=',')
header = next(data)
max_temp = -999
max_date = ''
low_temp = 999
low_date = ''
result_1 = []
result_2 = []

for row in data:
    if row[2] == '':
        row[2] = 0
    row[2] = float(row[2])
    if max_temp < row[2]:
        max_date = row[0]
        max_temp = row[2]
    if low_temp > row[2]:
        low_date = row[0]
        low_temp = row[2]
    if row[-1] != "":
        if row[0].split('-')[1] == '12' and row[0].split('-')[2] == '24':
            result_1.append(float(row[-1]))
            result_2.append(float(row[3]))       






plt.plot(result_1, color='r', label='Result 1')
plt.plot(result_2, color='b', label='Result 2')
plt.legend()
plt.show()

f.close()

print('서울 평균 기온이 가장 높은 날은',max_date, '이고 온도는', max_temp, '입니다')
print('서울 평균 기온이 가장 낮은 날은',low_date, '이고 온도는', low_temp, '입니다')